' PROGRAMA HECHO POR JOAN ALBA MALDONADO EL DIA 24/9/1996 PARA LA CASA SOSOFT
CLS
COLOR 25
PRINT TAB(27); "SS MECATA MORO 1.0"
LOCATE 4
PRINT
PRINT
COLOR 6
PRINT TAB(10); "PROGRAMA DE LA CASA SOSOFT LLAMADO MERCATA MORO V.1.0."
PRINT
PRINT TAB(10); "EN ESTE PROGRAMA PODRAS ''COMPRAR'' PRODUCTOS COMO SI ESTASES"
PRINT TAB(10); "EN UN MERCATA DE MOROS"
PRINT
COLOR 5
PRINT TAB(10); "ESTE ES EL VERDADERO SELLO PARA SABER QUE ES UN VERDADERO PROGRAMA SOSOFT:"
COLOR 29
PRINT
PRINT "                здддддд здддддд© здддддд здддддд© здддддд дддбддд "; : COLOR 3: PRINT "╘"; : COLOR 29
PRINT "                Ё       Ё      Ё Ё       Ё      Ё Ё          Ё"
PRINT "                юддддд© Ё      Ё юддддд© Ё      Ё цдддддд    Ё"
PRINT "                      Ё Ё      Ё       Ё Ё      Ё Ё          Ё"
PRINT "                дддддды юдддддды дддддды юдддддды а          а"
PRINT
COLOR 3
INPUT "PRESIONA RETURN (╝ы)                                                             "; RETURN1$
GOTO SIGUE1
SIGUE1:
CLS
PRINT "╗ ESTAMOS ENFRENTE DEL PORTAL DEL MERCATA MORO 1.0, QUE DESEAS, SALIR O ENTRAR ?"
COLOR 4
PRINT "           здддддддддддддддддддддддддбддддддддддддддддддддддддддддд©"
PRINT "           Ё"; : COLOR 23: PRINT "    ENTRADA AL MERCATA"; : COLOR 4: PRINT "   Ё"; : COLOR 23: PRINT "          MORO 1.0"; : COLOR 4: PRINT "           Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           ЁдддддддддддддддддддддддддшдддддддддддддддддддддддддддддЁ"
PRINT "           ЁдддддддддддддддддддддддддедддддддддддддддддддддддддддддЁ"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           Ё                         Ё                             Ё"
PRINT "           юдддддддддддддддддддддддддаддддддддддддддддддддддддддддды"
PRINT
COLOR 26
PRINT "1.- ENTRAR EN EL MERCATA"
PRINT "2.- NO ENTRAR EN EL MERCATA (SALIR)"
PRINT
INPUT "ELIGE UNA OPCION"; OP1

