'COLOR 1 azul marino
'COLOR 2 verde
'COLOR 3 verdeazul
'color 4 rojo
'color 5 rosa
'COLOR 6 dorado
'COLOR 7 blanko grisaceo
'COLOR 8 gris
'COLOR 9 azul chillon
'COLOR 10 verde chillon
'COLOR 11 verdeazul klaro
'COLOR 12 fuksia
'COLOR 13 rosa klaro
'COLOR 14 amarillo chillon
'COLOR 15 blanko
'COLOR 16 negro
'COLOR 17 azul marino parpadeante
'COLOR 18 verde parpadeante
'COLOR 19 verdeazul parpadeante
'COLOR 20 rojo parpadeante
'COLOR 21 rosa parpadeante
'COLOR 22 dorado parpadeante
'COLOR 23 blanko grisaceo parpadeante
'COLOR 24 gris parpadeante
'COLOR 25 azul parpadeante
'COLOR 26 verde chillon parpadeante
'COLOR 27 verdeazul flojo parpadeante
'COLOR 28 rosa fuksia parpadeante
'COLOR 29 rosa klaro parpadeante
'COLOR 30 amarillo chillon parpadeante
'COLOR 31 blanko parpadeante

