CLS
PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"

a = 2
b = a - 1
c = 15
d = c - 1
kolor = 2
DO
tekla$ = INKEY$
IF tekla$ = "p" THEN
CLS
COLOR kolor
PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
COLOR kolor + 1
LOCATE c, a: PRINT "É»": a = a + 1: b = a - 1: kolor = kolor + 1
END IF



IF tekla$ = "o" THEN
CLS
COLOR kolor
PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
COLOR kolor + 1
LOCATE c, b: PRINT "É»": b = b - 1: a = b + 1: kolor = kolor + 1
END IF
IF tekla$ = "a" THEN
CLS
COLOR kolor
PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
COLOR kolor + 1
LOCATE c, a: PRINT "É»": c = c + 1: d = c - 1: kolor = kolor + 1
END IF
IF tekla$ = "q" THEN
CLS
COLOR kolor
PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "³                                                                              ³"
PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
COLOR kolor + 1
LOCATE d, a: PRINT "É»": d = d - 1: c = d + 1: kolor = kolor + 1
END IF
IF kolor > 13 THEN kolor = 2
IF a < 3 THEN a = 78
IF b < 3 THEN b = 78
IF a > 78 THEN a = 3
IF b > 78 THEN b = 3
IF c > 22 THEN c = 2
IF d > 22 THEN d = 2
IF c < 2 THEN c = 22
IF d < 2 THEN d = 22
b = a - 1
LOOP

