COLOR 4
CLS
PRINT "зддддд©"
PRINT "Ё     Ё"
PRINT "юддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддд©"
PRINT "Ё       Ё"
PRINT "Ё       Ё"
PRINT "юддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддд©"
PRINT "Ё         Ё"
PRINT "Ё         Ё"
PRINT "Ё         Ё"
PRINT "юддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддд©"
PRINT "Ё           Ё"
PRINT "Ё           Ё"
PRINT "Ё           Ё"
PRINT "Ё           Ё"
PRINT "юддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддд©"
PRINT "Ё             Ё"
PRINT "Ё             Ё"
PRINT "Ё             Ё"
PRINT "Ё             Ё"
PRINT "Ё             Ё"
PRINT "юддддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддддд©"
PRINT "Ё               Ё"
PRINT "Ё               Ё"
PRINT "Ё               Ё"
PRINT "Ё               Ё"
PRINT "Ё               Ё"
PRINT "Ё               Ё"
PRINT "юддддддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддддддд©"
PRINT "Ё                 Ё"
PRINT "Ё                 Ё"
PRINT "Ё                 Ё"
PRINT "Ё                 Ё"
PRINT "Ё                 Ё"
PRINT "Ё                 Ё"
PRINT "Ё                 Ё"
PRINT "юддддддддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддддддддд©"
PRINT "Ё                   Ё"
PRINT "Ё                   Ё"
PRINT "Ё                   Ё"
PRINT "Ё                   Ё"
PRINT "Ё                   Ё"
PRINT "Ё                   Ё"
PRINT "Ё                   Ё"
PRINT "Ё                   Ё"
PRINT "юддддддддддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддддддддддд©"
PRINT "Ё                     Ё"
PRINT "Ё                     Ё"
PRINT "Ё                     Ё"
PRINT "Ё                     Ё"
PRINT "Ё                     Ё"
PRINT "Ё                     Ё"
PRINT "Ё                     Ё"
PRINT "Ё                     Ё"
PRINT "юддддддддддддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддддддддддддд©"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "Ё                       Ё"
PRINT "юддддддддддддддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддддддддддддддд©"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "Ё                         Ё"
PRINT "юддддддддддддддддддддддддды"
FOR x = 1 TO 2000: NEXT
CLS
PRINT "зддддддддддддддддддддддддддд©"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "Ё                           Ё"
PRINT "юддддддддддддддддддддддддддды"
COLOR 2
LOCATE 3, 13: PRINT "Gnosis"
COLOR 1
LOCATE 5, 12: PRINT "Presenta"
COLOR 6
FOR x = 1 TO 5000: NEXT
LOCATE 7, 8: PRINT "GNOSIS Magezine"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 8: PRINT "               "
FOR x = 1 TO 5000: NEXT
COLOR 9
LOCATE 7, 8: PRINT "GNOSIS Magezine"
COLOR 3
FOR x = 1 TO 5000: NEXT
LOCATE 7, 8: PRINT "               "
FOR x = 1 TO 5000: NEXT
LOCATE 7, 8: PRINT "G"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 9: PRINT "N"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 10: PRINT "O"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 11: PRINT "S"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 12: PRINT "I"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 13: PRINT "S"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 14: PRINT " "
COLOR 11
FOR x = 1 TO 5000: NEXT
LOCATE 7, 15: PRINT "M"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 16: PRINT "a"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 17: PRINT "g"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 18: PRINT "a"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 19: PRINT "z"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 20: PRINT "i"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 21: PRINT "n"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 22: PRINT "e"

LOCATE 3, 40: PRINT "Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 3, 40: PRINT "      "
LOCATE 4, 40: PRINT "Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 4, 40: PRINT "      "
LOCATE 5, 40: PRINT "Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 5, 40: PRINT "      "
LOCATE 6, 40: PRINT "Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 7, 40: PRINT "Gnosis"
LOCATE 6, 40: PRINT "      "
FOR x = 1 TO 5000: NEXT
LOCATE 8, 40: PRINT "Gnosis"
LOCATE 7, 40: PRINT "      "
FOR x = 1 TO 5000: NEXT
LOCATE 9, 40: PRINT "Gnosis"
LOCATE 8, 40: PRINT "      "
FOR x = 1 TO 5000: NEXT
LOCATE 10, 40: PRINT "Gnosis"
LOCATE 9, 40: PRINT "      "
FOR x = 1 TO 2000: NEXT
LOCATE 11, 40: PRINT "Gnosis"
LOCATE 10, 40: PRINT "      "
FOR x = 1 TO 2000: NEXT
LOCATE 12, 40: PRINT "Gnosis"
LOCATE 11, 40: PRINT "      "
FOR x = 1 TO 2000: NEXT
LOCATE 13, 40: PRINT "Gnosis"
LOCATE 12, 40: PRINT "      "
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "Gnosis"
LOCATE 13, 40: PRINT "      "
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT " Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "  Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "   Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "    Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "      Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "       Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "        Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "         Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "          Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "           Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "            Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "             Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "              Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "               Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                 Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                  Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                   Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                    Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 14, 40: PRINT "                     Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 14, 40: PRINT "                      Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 14, 40: PRINT "                       Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 14, 40: PRINT "                        Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                         Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                          Gnosis"
FOR x = 1 TO 5000: NEXT
LOCATE 14, 40: PRINT "                           Gnosis"
FOR x = 1 TO 2000: NEXT
LOCATE 14, 40: PRINT "                            Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "                             Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "                              Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "                               Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "                                Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "                                 Gnosis"
FOR x = 1 TO 800: NEXT
LOCATE 14, 40: PRINT "                                  Gnosis"
FOR x = 1 TO 500: NEXT
LOCATE 14, 40: PRINT "                                   Gnosis"
PLAY "acdeeedba"
CLS






