INICIO:
CLS
PRINT
PRINT
CALLE:
PRINT "    BIEN BENIDO, HAS ENTRADO EN EL MERCATA DE LOS SUE¥OS Y DE LAS DELICIAS..."
PRINT "      ...HAS ENTRADO EN EL SUPER MERCADO ''JOAN'', DE LA CASA JOANSOFT"
PRINT
PRINT "                      JS(JOANSOFT) MERCATA JOAN V.1.0 "
PRINT
PRINT "PARA QUE TE METAS EN LA BOLA LO QUE HACE ESTE PROGRAMA TE DIRE:"
PRINT "ESTE ES UN PROGRAMA QUE SIMULA UN SUPER MERCADO LLAMADO JOAN"
PRINT "ESTE PROGRAMA LLEVA EN LA MEMORIA COMO SI DIJESEMOS ''EL MERCADO VIRTUAL,"
PRINT "DONDE SE PODRA IR HA COMPRAR A LA SECCIONES FABORITAS."
PRINT
MENU1:
PRINT "1.- ENTRADA AL MERCADO ''JOAN''"
PRINT "2.- NADA, NO ENTRO EN EL MERCADO VIRTUAL"
PRINT "3.- PRIMERO QUIERO VER LAS NORMAS Y PLANOS DEL MERCADO"
PRINT
INPUT "ELIGE UNA OPCION"; OP1
ON OP1 GOTO ENTRADA, SALIDA, LEEME
GOTO INICIO
ENTRADA:
CLS
PRINT
COLOR (12)
PRINT "                               MERCATA JOAN          "
PRINT
COLOR (17)
PRINT "                                 ENTRADA"
COLOR (3)
PRINT
PRINT TAB(19); " -----------------------------------"
PRINT TAB(19); "|                |                  |"
PRINT TAB(19); "|                |                  |"
PRINT TAB(19); "|________________|__________________|"
PRINT TAB(19); "|________________|__________________|"
PRINT TAB(19); "|               _|_                 |"
PRINT TAB(19); "|              |_ú_|                |"
PRINT TAB(19); "|                |                  |"
PRINT TAB(19); "|                |                  |"
PRINT TAB(19); "|                |                  |"
PRINT TAB(19); " -----------------------------------"
PRINT


SALIDA:

LEEME:

