CLS
LOCATE 5
PRINT "HOLA, ESTE ES EL JUEGO DE LA CASA JOANSOFT, Y CON EL TE DIVERTIRAS"
PRINT "MUCHO, EL JUEGO CONSISTE EN:"
PRINT
PRINT "ELEGIR DOS CARTAS, Y HACER PAREJA"
PRINT
PRINT "1.- JUGAR"
PRINT "2.- SALIR"
PRINT
INPUT "ELIGE UNA OPCION"; OP1
ON OP1 GOTO JUGAR, SALIR

JUGAR:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    1    Ё Ё    4    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    3    Ё Ё    6    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT
INPUT "ELIGE LA PRIMERA CARTA"; CARTA1
IF CARTA1 = 1 THEN GOTO CART1
IF CARTA1 = 2 THEN GOTO CART2
IF CARTA1 = 3 THEN GOTO CART3
IF CARTA1 = 4 THEN GOTO CART4
IF CARTA1 = 5 THEN GOTO CART5
IF CARTA1 = 6 THEN GOTO CART6
IF CARTA1 = 7 THEN GOTO CART7
CLS : GOTO JUGAR
CART1:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    ╬    Ё Ё    4    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    3    Ё Ё    6    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "INTRO PARA CONTINUAR"; HOLA
GOTO CARTS1

CART2:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    1    Ё Ё    4    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    ─    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    3    Ё Ё    6    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "INTRO PARA CONTINUAR"; HOLA
GOTO JUGAR

CART3:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    1    Ё Ё    4    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    ╫    Ё Ё    6    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "INTRO PARA CONTINUAR"; HOLA
GOTO JUGAR

CART4:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    1    Ё Ё    {    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    3    Ё Ё    6    Ё "
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "INTRO PARA CONTINUAR"; HOLA
GOTO JUGAR

CART5:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    1    Ё Ё    4    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    ╬    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    3    Ё Ё    6    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "INTRO PARA CONTINUAR"; HOLA
GOTO JUGAR

CART6:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    1    Ё Ё    4    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    3    Ё Ё    ─    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "INTRO PARA CONTINUAR"; HOLA
GOTO JUGAR

CART7:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    1    Ё Ё    4    Ё Ё    ╫    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    ╫    Ё Ё    6    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "INTRO PARA CONTINUAR"; HOLA
GOTO JUGAR

CARTS1:
CLS
PRINT
PRINT "зддддддддд© зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё    ╬    Ё Ё    4    Ё Ё    7    Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    2    Ё Ё    5    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
PRINT "зддддддддд© зддддддддд©"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё    3    Ё Ё    6    Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "Ё         Ё Ё         Ё"
PRINT "юддддддддды юддддддддды"
INPUT "ELIGE LA SEGUNDA CARTA"; CARTA2
IF CARTA2 = 2 THEN GOTO CART2
IF CARTA2 = 3 THEN GOTO CART3
IF CARTA2 = 4 THEN GOTO CART4
IF CARTA2 = 5 THEN GOTO CART5
IF CARTA2 = 6 THEN GOTO CART6
IF CARTA2 = 7 THEN GOTO CART7




 

SALIR:

